# Use microsoft devconatiner debian base latest
FROM mcr.microsoft.com/devcontainers/base:debian

# Install python3 and pip
RUN apt-get update && apt-get install -y python3 python3-pip

# Install nodejs and npm
RUN apt-get install -y nodejs npm
